# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serveless-selenium-ruby27
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  region: us-east-1
  profile: rakmy

custom:
  hooks:
    before:deploy:deploy:
      - docker build -t chromedriver .
      - docker run --rm -v "$PWD"/build:/opt chromedriver

layers:
  chromedriver:
    path: build
    compatibleRuntimes:
      - ruby2.7

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-ruby-layer
  - serverless-hooks-plugin